kevlu8/PZChessBot

bot/main.cpp
engine/search.cpp

Fixed mem leak

---

README.md
TODO
engine/eval.cpp

Since our repo appears to be gaining modest attention, I have changed all the references of French into English so more people can understand.

touch up readme and some comments in code

---

engine/bitboard.cpp
engine/bitboard.hpp
engine/ttable.cpp
engine/ttable.hpp

- Adds zobrist hash to the board state
- Adds foundation for transposition table

Add zobrist hashing

---

.github/workflows/c-cpp.yml
CMakeLists.txt
bot/main.cpp
engine/bitboard.cpp
engine/bitboard.hpp
engine/compile
engine/eval.cpp
engine/eval.hpp
engine/includes.hpp
engine/main.cpp
engine/move.hpp
engine/search.cpp
engine/search.hpp
engine/ttable.cpp
engine/ttable.hpp

- Fix quiescence search
- Harshly penalize squares a7 and h7 for the bishop to avoid trapping

Fix quiescence search and add base for hashtables

---

.gitignore
CMakeLists.txt
engine/bitboard.cpp
engine/bitboard.hpp
engine/includes.hpp
engine/pzstl/vector.hpp
engine/search.cpp
engine/search.hpp
engine/ttable.hpp
test/perfts.cpp
test/search.cpp

- Tweak compilation script
- Fix threefold being interpreted as *two*fold
- Fix `go infinite`
- Bump version number

Minor bug fixes, preparing for next release

---

Makefile
engine/eval.cpp
engine/includes.hpp
engine/main.cpp
engine/search.cpp
engine/search.hpp

- Bump version number
- Small bugfixes and compatibility fixes

Finalize for release

---

engine/search.cpp

```
Elo   | 8.70 +- 6.87 (95%)
LLR   | 2.96 (-2.94, 2.94) [0.00, 10.00]
Games | N: 4756 W: 1280 L: 1161 D: 2315
Penta | [133, 530, 962, 591, 162]
```
https://sscg13.pythonanywhere.com/test/111/

bench: 120629 add lmr to main

---

engine/search.cpp

Loses a small amount of ELO but it is important to have full PV printing. 
```
Elo   | -5.11 +- 4.06 (95%)
LLR   | -2.98 (-2.94, 2.94) [-10.00, 0.00]
Games | N: 5368 W: 1061 L: 1140 D: 3167
Penta | [51, 360, 1929, 305, 39]
```
https://sscg13.pythonanywhere.com/test/135/

bench: 273173 add pv printing

---

engine/search.cpp

```
Elo   | 16.72 +- 10.35 (95%)
LLR   | 2.98 (-2.94, 2.94) [0.00, 10.00]
Games | N: 1580 W: 349 L: 273 D: 958
Penta | [17, 164, 371, 202, 36]
```
https://sscg13.pythonanywhere.com/test/144/

bench: 184778 add counter-move history

---

engine/search.cpp

Literally like idk whats going on anymore i just wanna release 2.0 lol

bench: 192920 fix pvs pv issue, also partially fixing low nps issue

---

engine/search.cpp

Instead of doing expensive floating point multiplications and logarithms, precompute the results in a table
Uhh I should probably SPRT but like this literally cannot lose elo

Precompute LMR tables

---

engine/bitboard.cpp

Ok wtf?? Idk why but this loses elo, but it's necessary for correctness so I'm merging it anyways

Fix bug in castling handling in zobrist

---

Makefile
engine/bitboard.cpp
engine/bitboard.hpp
engine/search.cpp
engine/search.hpp

```
Elo   | 2.48 +- 1.96 (95%)
LLR   | 2.96 (-2.94, 2.94) [0.00, 5.00]
Games | N: 41582 W: 8045 L: 7748 D: 25789
Penta | [598, 4601, 10148, 4794, 650]
```
https://sscg13.pythonanywhere.com/test/353/
The longest test I've had by far

Add pawn correction history

---

engine/search.cpp
engine/search.hpp

```
Elo   | 5.39 +- 3.80 (95%)
Games | N: 9418 W: 1567 L: 1421 D: 6430
Penta | [95, 929, 2515, 1075, 95]
```
https://sscg13.pythonanywhere.com/test/519/
Bench: 174049

Add SPSA values

---

engine/bitboard.cpp
engine/bitboard.hpp
engine/main.cpp
engine/ttable.cpp
engine/ttable.hpp

And change TT replacement scheme
```
Elo   | 65.28 +- 14.77 (95%)
Games | N: 700 W: 246 L: 116 D: 338
Penta | [1, 40, 158, 130, 21]
```
https://sscg13.pythonanywhere.com/test/535/
Bench: 174264

Do not reset TT on `position` command

---

engine/includes.hpp
engine/search.cpp
engine/search.hpp

```
Elo   | 4.98 +- 3.66 (95%)
LLR   | 2.95 (-2.25, 2.89) [0.00, 5.00]
Games | N: 11926 W: 2895 L: 2724 D: 6307
Penta | [145, 1389, 2728, 1552, 149]
```
https://sscg13.pythonanywhere.com/test/552/
No idea what bench is but we'll find out

Add Singular Extensions

---

engine/bitboard.cpp
engine/bitboard.hpp
engine/includes.hpp
engine/main.cpp
engine/search.cpp
engine/search.hpp

Terminal is now much nicer to look at and use

Add pretty output

---

engine/eval.cpp

```
Elo   | 9.48 +- 5.47 (95%)
Games | N: 4914 W: 894 L: 760 D: 3260
Penta | [49, 492, 1267, 574, 75]
```
https://sscg13.pythonanywhere.com/test/727/
Bench: 1363613

Add bishop pair bonus

---

engine/eval.cpp

```
Elo   | 11.27 +- 6.44 (95%)
Games | N: 4750 W: 1240 L: 1086 D: 2424
Penta | [83, 555, 989, 621, 127]
```
https://sscg13.pythonanywhere.com/test/749/
Bench: 814024

Add king safety metric

---

engine/search.hpp

```
Elo   | 2.83 +- 2.28 (95%)
Games | N: 36600 W: 8763 L: 8465 D: 19372
Penta | [733, 4400, 7791, 4588, 788]
```
https://sscg13.pythonanywhere.com/test/744/
Bench: 549005

Change RFP threshold to 100

---

engine/search.cpp

```
Elo   | 10.98 +- 5.88 (95%)
LLR   | 2.97 (-2.25, 2.89) [0.00, 5.00]
Games | N: 4178 W: 1005 L: 873 D: 2300
Penta | [29, 453, 1009, 553, 45]
```
https://sscg13.pythonanywhere.com/test/780/
Bench: 972363

Only allow tt cutoffs in PV and fix TT handling

---

engine/main.cpp
engine/search.cpp
engine/search.hpp

MultiPV 3 vs 1
```
Elo   | 57.20 +- 14.41 (95%)
SPRT  | D=10 Threads=1 Hash=32MB
LLR   | 3.37 (-2.25, 2.89) [0.00, 5.00]
Games | N: 1048 W: 406 L: 235 D: 407
Penta | [13, 81, 203, 176, 51]
```
https://sscg13.pythonanywhere.com/test/807/
Bench: 972363

Add MultiPV support

---

engine/search.cpp

whjatever didn't pass but like cmon
```
Elo   | 1.12 +- 1.29 (95%)
LLR   | 1.08 (-2.25, 2.89) [0.00, 3.00]
Games | N: 85976 W: 19161 L: 18885 D: 47930
Penta | [676, 10360, 20709, 10498, 745]
```
https://sscg13.pythonanywhere.com/test/846/
Bench: 855728

Cutnode negative extensions

---

engine/bitboard.cpp
engine/bitboard.hpp
engine/search.cpp

```
Elo   | 7.73 +- 4.86 (95%)
Games | N: 6340 W: 1552 L: 1411 D: 3377
Penta | [57, 716, 1492, 839, 66]
```
http://sscg13.pythonanywhere.com/test/943/
Bench: 776639

Add corrhist based on a non-pawn position hash

---

engine/search.cpp

```
Elo   | 8.80 +- 5.15 (95%)
LLR   | 2.97 (-2.25, 2.89) [0.00, 5.00]
Games | N: 5372 W: 1286 L: 1150 D: 2936
Penta | [33, 617, 1258, 737, 41]
```
https://sscg13.pythonanywhere.com/test/1023/
Bench: 662241

Add complexity time management

---

.gitignore
Makefile
engine/search.cpp

```
Elo   | 14.74 +- 6.96 (95%)
Games | N: 2878 W: 723 L: 601 D: 1554
Penta | [13, 305, 698, 393, 30]
```
https://sscg13.pythonanywhere.com/test/1081/
Bench: 1038523 - No functional change

Improve makefile and add LTO

---

engine/movetimings.hpp
engine/search.cpp

Passed STC
```
Elo   | 24.38 +- 8.99 (95%)
LLR   | 3.00 (-2.25, 2.89) [0.00, 5.00]
Games | N: 1784 W: 481 L: 356 D: 947
Penta | [11, 165, 425, 270, 21]
```
https://sscg13.pythonanywhere.com/test/1095/
Passed LTC
```
Elo   | 16.34 +- 7.14 (95%)
SPRT  | 40.0+0.40s Threads=1 Hash=128MB
Games | N: 2362 W: 544 L: 433 D: 1385
Penta | [2, 233, 613, 318, 15]
```
https://sscg13.pythonanywhere.com/test/1096/
Bench: 5653116

Add soft node time management

---

engine/search.cpp

```
Elo   | 5.22 +- 3.73 (95%)
Games | N: 10124 W: 2371 L: 2219 D: 5534
Penta | [71, 1177, 2418, 1321, 75]
```
https://sscg13.pythonanywhere.com/test/1119/
Bench: 5300664

Do not update corrhist on mates

---

engine/search.cpp

```
Elo   | 1.49 +- 3.17 (95%)
LLR   | 2.95 (-2.25, 2.89) [-5.00, 0.00]
Games | N: 13546 W: 3158 L: 3100 D: 7288
Penta | [73, 1640, 3311, 1654, 95]
```
https://sscg13.pythonanywhere.com/test/1176/
Bench: 9500188

Remove counter-move history

---

engine/nnue/network.hpp

```
Elo   | 72.68 +- 25.37 (95%)
LLR   | 3.08 (-2.25, 2.89) [0.00, 10.00]
Games | N: 388 W: 175 L: 95 D: 118
Penta | [2, 30, 80, 50, 32]
```
https://sscg13.pythonanywhere.com/test/1245/
pznet8.nnue
Bench: 1392343

Add 64HL net

---

engine/nnue/network.hpp

```
Elo   | 63.92 +- 15.84 (95%)
Games | N: 786 W: 305 L: 162 D: 319
Penta | [6, 54, 159, 139, 35]
```
https://sscg13.pythonanywhere.com/test/1263/
Bench: 1546936

Add 128HL network
