- engine/bitboard.hpp
There appears to be an error in the file `bitboard.hpp` that makes the operator `!=` on the `Move` struct the same as `==`. Therefore, I have changed the file so that `!=` represents inequality.
> Update bitboard.hpp to fix the bug that made == the same as !=

- engine/search.cpp
```
Elo   | 147.51 +- 30.93 (95%)
LLR   | 3.28 (-2.94, 2.94) [0.00, 10.00]
Games | N: 262 W: 128 L: 23 D: 111
Penta | [0, 7, 40, 56, 28]
```
https://sscg13.pythonanywhere.com/test/130/
> bench: 273173 add history

- engine/search.cpp
```
Elo   | 53.52 +- 21.69 (95%)
LLR   | 3.08 (-2.94, 2.94) [-10.00, 0.00]
Games | N: 458 W: 135 L: 65 D: 258
Penta | [6, 32, 101, 66, 24]
```
https://sscg13.pythonanywhere.com/test/131
Finally abandoning the scuffed old move ordering in favor of proper ordering
> bench: 273173 Switch to proper move ordering scheme

- engine/search.cpp
```
Elo   | 5.99 +- 4.79 (95%)
LLR   | 3.01 (-2.94, 2.94) [0.00, 10.00]
Games | N: 7710 W: 1631 L: 1498 D: 4581
Penta | [129, 865, 1755, 956, 150]
```
https://sscg13.pythonanywhere.com/test/157/
should probably tune a bit
> bench: 96074 add IIR

- engine/bitboard.cpp
- engine/eval.cpp
- engine/search.cpp
```
Elo   | -0.70 +- 4.34 (95%)
LLR   | 3.01 (-2.94, 2.94) [-10.00, 0.00]
Games | N: 9414 W: 1926 L: 1945 D: 5543
Penta | [165, 1139, 2125, 1106, 172]
```
https://sscg13.pythonanywhere.com/test/160/
> Fix 50-move rule handling - also fixes a part of illegal PV

- engine/search.cpp
- engine/search.hpp
```
Elo   | 17.56 +- 7.97 (95%)
LLR   | 2.99 (-2.94, 2.94) [0.00, 5.00]
Games | N: 2772 W: 620 L: 480 D: 1672
Penta | [32, 290, 643, 348, 73]
```
https://sscg13.pythonanywhere.com/test/185/
Some tweaking should be done on RFP_THRESHOLD before merging
> Add reverse futility pruning

- engine/search.cpp
```
Elo   | 8.28 +- 5.17 (95%)
LLR   | 2.97 (-2.94, 2.94) [0.00, 5.00]
Games | N: 6546 W: 1396 L: 1240 D: 3910
Penta | [111, 697, 1519, 817, 129]
```
https://sscg13.pythonanywhere.com/test/192/
> bench: 63404 disable nmp when pieces < 8

- engine/search.cpp
This guarantees `killer[0]` and `killer[1]` are different, and consequently bonuses have been adjusted.
```
Elo   | 3.46 +- 2.78 (95%)
LLR   | 2.95 (-2.94, 2.94) [0.00, 5.00]
Games | N: 22970 W: 4833 L: 4604 D: 13533
Penta | [424, 2567, 5293, 2758, 443]
```
https://sscg13.pythonanywhere.com/test/226/
> Prevent storing of the same killer move

- engine/search.cpp
- engine/search.hpp
```
Elo   | 9.32 +- 5.52 (95%)
LLR   | 3.02 (-2.94, 2.94) [0.00, 5.00]
Games | N: 5740 W: 1210 L: 1056 D: 3474
Penta | [87, 620, 1341, 696, 126]
```
https://sscg13.pythonanywhere.com/test/290/
fp FINALLY passed
> Add futility pruning

- engine/nnue/egnn.cpp
- engine/nnue/network.cpp
```
Elo   | 7.39 +- 4.93 (95%)
LLR   | 2.98 (-2.94, 2.94) [0.00, 5.00]
Games | N: 8226 W: 2008 L: 1833 D: 4385
Penta | [189, 912, 1757, 1045, 210]
```
https://sscg13.pythonanywhere.com/test/292/
> Vectorize nnue_eval()

- engine/search.hpp
```
Elo   | 17.29 +- 8.07 (95%)
LLR   | 2.95 (-2.94, 2.94) [0.00, 5.00]
Games | N: 2876 W: 669 L: 526 D: 1681
Penta | [38, 324, 606, 397, 73]
```
https://sscg13.pythonanywhere.com/test/296/
> add spsa tuned values

- engine/includes.hpp
- engine/search.cpp
Change history to use the gravity formula as well as giving maluses
```
Elo   | 16.24 +- 7.72 (95%)
LLR   | 2.98 (-2.94, 2.94) [0.00, 5.00]
Games | N: 3126 W: 752 L: 606 D: 1768
Penta | [48, 344, 654, 448, 69]
```
https://sscg13.pythonanywhere.com/test/299/
> add gravity for history

- engine/search.cpp
```
Elo   | 14.13 +- 7.09 (95%)
LLR   | 2.98 (-2.94, 2.94) [0.00, 5.00]
Games | N: 3568 W: 816 L: 671 D: 2081
Penta | [59, 362, 817, 467, 79]
```
https://sscg13.pythonanywhere.com/test/300/
> test adding capture history

- engine/includes.hpp
- engine/movetimings.hpp
- engine/search.cpp
- engine/search.hpp
```
Elo   | 11.52 +- 6.21 (95%)
LLR   | 3.00 (-2.94, 2.94) [0.00, 5.00]
Games | N: 4344 W: 904 L: 760 D: 2680
Penta | [61, 444, 1044, 536, 87]
```
https://sscg13.pythonanywhere.com/test/317/
> bench: 242114 add spsa values

- engine/search.cpp
```
Elo   | 10.75 +- 5.20 (95%)
LLR   | 3.04 (-2.94, 2.94) [0.00, 5.00]
Games | N: 3396 W: 719 L: 614 D: 2063
Penta | [3, 270, 1050, 369, 6]
```
https://sscg13.pythonanywhere.com/test/373/
Tested on endgame book
> Change NMP to avoid pruning in non-pawn endgames

- engine/search.cpp
```
Elo   | 3.01 +- 2.38 (95%)
LLR   | 3.04 (-2.94, 2.94) [0.00, 5.00]
Games | N: 25544 W: 4402 L: 4181 D: 16961
Penta | [296, 2680, 6626, 2847, 323]
```
https://sscg13.pythonanywhere.com/test/462/
> Change move selection to use a lazy method

- engine/search.cpp
- engine/search.hpp
```
Elo   | 18.01 +- 7.88 (95%)
Games | N: 2394 W: 590 L: 466 D: 1338
Penta | [15, 248, 563, 340, 31]
```
https://sscg13.pythonanywhere.com/test/563/
Bench: 63128
> Use improving flag to lower RFP margin

- engine/search.cpp
- engine/search.hpp
```
Elo   | 20.82 +- 8.48 (95%)
LLR   | 2.94 (-2.25, 2.89) [0.00, 5.00]
Games | N: 2122 W: 556 L: 429 D: 1137
Penta | [18, 207, 494, 314, 28]
```
https://sscg13.pythonanywhere.com/test/562/
Bench: 90623
> Add history pruning

- engine/search.cpp
STC:
```
Elo   | 7.22 +- 4.66 (95%)
Games | N: 6736 W: 1569 L: 1429 D: 3738
Penta | [45, 792, 1573, 894, 64]
```
https://sscg13.pythonanywhere.com/test/573/
Prelim. LTC:
```
Elo   | 17.24 +- 13.88 (95%)
SPRT  | 40.0+0.40s Threads=1 Hash=128MB
LLR   | 1.01 (-2.25, 2.89) [-5.00, 0.00]
Games | N: 706 W: 171 L: 136 D: 399
Penta | [2, 72, 176, 95, 8]
```
https://sscg13.pythonanywhere.com/test/583/
wtf is this scaling?
Bench: 679159
> Add QSearch futility pruning

- engine/search.cpp
```
Elo   | 6.44 +- 4.34 (95%)
LLR   | 2.96 (-2.25, 2.89) [0.00, 5.00]
Games | N: 8366 W: 2020 L: 1865 D: 4481
Penta | [83, 981, 1930, 1076, 113]
```
https://sscg13.pythonanywhere.com/test/622/
Bench: 866499
> Reduce more if tentry is a capture

- engine/search.cpp
```
Elo   | 18.06 +- 7.79 (95%)
Games | N: 2388 W: 594 L: 470 D: 1324
Penta | [21, 233, 559, 363, 18]
```
https://sscg13.pythonanywhere.com/test/638/
Bench: 491836
> fix killer move handling

- engine/movegen.cpp
- engine/search.cpp
```
Elo   | 23.99 +- 9.36 (95%)
Games | N: 1900 W: 536 L: 405 D: 959
Penta | [22, 178, 432, 283, 35]
```
https://sscg13.pythonanywhere.com/test/677/
Bench: 648426
> skip low depth nodes with bad see

- engine/search.cpp
```
Elo   | 3.29 +- 2.64 (95%)
Games | N: 21248 W: 4799 L: 4598 D: 11851
Penta | [179, 2542, 5017, 2671, 215]
```
https://sscg13.pythonanywhere.com/test/718/
Bench: 575060
> Raise the depth of the entire node when SE is done

- engine/eval.cpp
```
Elo   | 79.42 +- 17.18 (95%)
LLR   | 2.99 (-2.25, 2.89) [0.00, 5.00]
Games | N: 672 W: 234 L: 83 D: 355
Penta | [3, 42, 125, 133, 33]
```
https://sscg13.pythonanywhere.com/test/729/
Bench: 684412
> Taper pawn and king in endgame

- engine/eval.cpp
```
Elo   | 148.39 +- 28.61 (95%)
LLR   | 2.96 (-2.25, 2.89) [0.00, 5.00]
Games | N: 484 W: 274 L: 79 D: 131
Penta | [3, 28, 60, 73, 78]
```
https://sscg13.pythonanywhere.com/test/745/
Bench: 787085
> Switch to also tapering material

- engine/search.cpp
```
Elo   | 7.56 +- 5.70 (95%)
LLR   | 2.89 (-2.25, 2.89) [-5.00, 0.00]
Games | N: 4276 W: 1001 L: 908 D: 2367
Penta | [23, 485, 1046, 544, 40]
```
https://sscg13.pythonanywhere.com/test/847/
Bench: 755363
> Do not do eval correction when ttEval is mate

- engine/search.cpp
Passed STC:
```
Elo   | 10.03 +- 5.70 (95%)
Games | N: 4678 W: 1146 L: 1011 D: 2521
Penta | [39, 534, 1067, 651, 48]
```
https://sscg13.pythonanywhere.com/test/881/
Bench: 893263
> Return average of eval and beta in RFP

- engine/search.cpp
Reduces number of expensive eval calls
Passed STC:
```
Elo   | 8.85 +- 5.24 (95%)
Games | N: 5260 W: 1238 L: 1104 D: 2918
Penta | [28, 612, 1246, 686, 58]
```
https://sscg13.pythonanywhere.com/test/905/
Bench: 793898
> Use TT eval when available in QS

- engine/search.cpp
```
Elo   | 4.84 +- 3.57 (95%)
LLR   | 2.93 (-2.25, 2.89) [0.00, 5.00]
Games | N: 11850 W: 2824 L: 2659 D: 6367
Penta | [109, 1387, 2792, 1504, 133]
```
https://sscg13.pythonanywhere.com/test/915/
Bench: 770044
> Reduce cutnodes more

- engine/includes.hpp
- engine/search.cpp
```
Elo   | 6.66 +- 4.41 (95%)
Games | N: 7458 W: 1769 L: 1626 D: 4063
Penta | [53, 861, 1781, 958, 76]
```
https://sscg13.pythonanywhere.com/test/914/
Bench: 556558
> Add corrhist based on previous move

- engine/search.cpp
```
Elo   | 5.17 +- 3.75 (95%)
Games | N: 10560 W: 2521 L: 2364 D: 5675
Penta | [94, 1212, 2536, 1319, 119]
```
https://sscg13.pythonanywhere.com/test/917/
Bench: 692221
> Use a dynamic PVS SEE margin

- engine/search.cpp
```
Elo   | 2.68 +- 2.17 (95%)
Games | N: 32562 W: 7694 L: 7443 D: 17425
Penta | [363, 3799, 7716, 4030, 373]
```
https://sscg13.pythonanywhere.com/test/942/
Bench: 1205222
> Allow razoring to depth 8

- engine/search.cpp
```
Elo   | 5.45 +- 3.83 (95%)
LLR   | 2.98 (-2.25, 2.89) [0.00, 5.00]
Games | N: 10070 W: 2366 L: 2208 D: 5496
Penta | [82, 1186, 2355, 1316, 96]
```
https://sscg13.pythonanywhere.com/test/947/
Bench: 939386
> Do shallower NMP when far exceeding beta

- engine/search.cpp
```
Elo   | 7.10 +- 4.59 (95%)
Games | N: 6896 W: 1702 L: 1561 D: 3633
Penta | [57, 772, 1658, 895, 66]
```
https://sscg13.pythonanywhere.com/test/952/
Bench: 697304
> Only do LMR at depth over 2

- engine/search.cpp
```
Elo   | 5.77 +- 4.02 (95%)
Games | N: 8978 W: 2087 L: 1938 D: 4953
Penta | [74, 1025, 2153, 1152, 85]
```
https://sscg13.pythonanywhere.com/test/1026/
Bench: 744211
> Disallow NMP at low depth

- engine/search.cpp
```
Elo   | 7.36 +- 4.71 (95%)
Games | N: 6614 W: 1570 L: 1430 D: 3614
Penta | [40, 794, 1524, 884, 65]
```
https://sscg13.pythonanywhere.com/test/1028/
Bench: 744211
> Test adding TT prefetching

- engine/search.cpp
```
Elo   | 2.81 +- 2.29 (95%)
Games | N: 27246 W: 6233 L: 6013 D: 15000
Penta | [207, 3217, 6585, 3377, 237]
```
https://sscg13.pythonanywhere.com/test/1029/
Bench: 744211
> Do not do complexity TM for captures, promotions, and in check

- engine/search.cpp
Passed STC
```
Elo   | 7.46 +- 4.65 (95%)
LLR   | 3.04 (-2.25, 2.89) [0.00, 5.00]
Games | N: 6850 W: 1665 L: 1518 D: 3667
Penta | [51, 797, 1600, 908, 69]
```
https://sscg13.pythonanywhere.com/test/1063/
Passed LTC
```
Elo   | 8.78 +- 5.04 (95%)
SPRT  | 40.0+0.40s Threads=1 Hash=128MB
Games | N: 4790 W: 1068 L: 947 D: 2775
Penta | [8, 522, 1230, 611, 24]
```
https://sscg13.pythonanywhere.com/test/1064/
Bench: 788726
> Do more reduction in LMR

- engine/search.cpp
```
Elo   | 9.93 +- 5.59 (95%)
Games | N: 4552 W: 1108 L: 978 D: 2466
Penta | [24, 518, 1081, 610, 43]
```
https://sscg13.pythonanywhere.com/test/1079/
Bench: 1038523
> Do not allow NMP in singular searches

- engine/search.cpp
```
Elo   | 5.65 +- 4.92 (95%)
LLR   | 2.93 (-2.25, 2.89) [-5.00, 0.00]
Games | N: 5346 W: 1293 L: 1206 D: 2847
Penta | [22, 591, 1382, 634, 44]
```
https://sscg13.pythonanywhere.com/test/1098/
Bench: 15384886
> Fix node counting

- engine/search.cpp
```
Elo   | 1.04 +- 2.91 (95%)
LLR   | 2.94 (-2.25, 2.89) [-5.00, 0.00]
Games | N: 15994 W: 3724 L: 3676 D: 8594
Penta | [93, 1916, 3949, 1928, 111]
```
https://sscg13.pythonanywhere.com/test/1116/
Bench: 7593665
> Attempt to fix mate score handling

- engine/search.cpp
```
Elo   | 12.24 +- 6.28 (95%)
Games | N: 3578 W: 918 L: 792 D: 1868
Penta | [23, 378, 874, 478, 36]
```
https://sscg13.pythonanywhere.com/test/1121/
Bench: 5605749
> Only do IIR on PV and Cutnodes

- engine/search.cpp
```
Elo   | 4.84 +- 3.55 (95%)
Games | N: 10988 W: 2589 L: 2436 D: 5963
Penta | [69, 1270, 2683, 1383, 89]
```
https://sscg13.pythonanywhere.com/test/1133/
Bench: 6226690
> Use ttDepth - 3 in SE

- engine/search.cpp
```
Elo   | 8.53 +- 5.12 (95%)
Games | N: 5376 W: 1327 L: 1195 D: 2854
Penta | [31, 607, 1300, 699, 51]
```
https://sscg13.pythonanywhere.com/test/1147/
Bench: 6203851
> Change history update formula

- engine/search.cpp
```
Elo   | 18.56 +- 7.82 (95%)
LLR   | 2.93 (-2.25, 2.89) [0.00, 5.00]
Games | N: 2248 W: 585 L: 465 D: 1198
Penta | [10, 223, 551, 317, 23]
```
https://sscg13.pythonanywhere.com/test/1151/
Bench: 6288578
> Do more LMR in nonPV nodes

- engine/search.cpp
```
Elo   | 8.04 +- 4.77 (95%)
LLR   | 2.98 (-2.25, 2.89) [0.00, 5.00]
Games | N: 5618 W: 1347 L: 1217 D: 3054
Penta | [26, 603, 1424, 727, 29]
```
https://sscg13.pythonanywhere.com/test/1171/
Bench: 9414793
> 2-ply conthist

- engine/eval.cpp
- engine/nnue/network.hpp
```
Elo   | 25.15 +- 13.96 (95%)
LLR   | 3.03 (-2.25, 2.89) [0.00, 10.00]
Games | N: 1204 W: 416 L: 329 D: 459
Penta | [28, 124, 236, 161, 53]
```
https://sscg13.pythonanywhere.com/test/1248/
Bench: 1364035
> Add output buckets
